import type { Metadata } from "next";
import "./globals.css";
import "./css/clash-display.css";
import "./css/satoshi.css";
import "./css/animation.css";
// import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Buy Followers, Like, Subscribers, Views & Grow Exponentially",
  description: "Generated by Sunlight",
  icons: "/image/logo.png",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <MySVG /> */}
        {/* <SessionProvider>{children}</SessionProvider> */}
        {children}
      </body>
    </html>
  );
}
